name: df
channels:
  - conda-forge
  - bioconda
  - defaults
  - pypi
dependencies:
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - et_xmlfile=1.1.0
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icu=58.2
  - jpeg=9e
  - libclang=12.0.0
  - libffi=3.4.2
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.37
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - openpyxl=3.0.10
  - openssl=1.1.1q
  - packaging=21.3
  - pcre=8.45
  - pip=22.1.2
  - ply=3.11
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.9.13
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - setuptools=63.4.1
  - sip=6.6.2
  - sqlite=3.39.2
  - toml=0.10.2
  - tzdata=2022c
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - labelimg==1.8.6
    - labeling==0.1.13
    - lxml==4.9.3
    - numpy==1.23.3
    - opencv-python==4.6.0.66
    - pillow==9.5.0
    - scipy==1.11.1
    - tifffile==2023.7.18
